services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: disc-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - /var/opt/mssql
  #   - mssql-data:/var/opt/mssql

    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -Q 'SELECT 1' -C -b"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  mongo:
    image: mongo:7
    container_name: disc-mongo
    ports:
      - "27018:27017"   # external:internal
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--username", "root", "--password", "${MONGO_PASSWORD}", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  neo4jdb:
    image: neo4j:latest
    container_name: disc-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_heap_max__size=1G
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "${NEO4J_USER}", "-p", "${NEO4J_PASSWORD}", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend-disc:
    container_name: backend-disc
    build:
      context: .               
      dockerfile: backend-disc/backend-disc/Dockerfile.dev
    env_file:
      - .env  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_SECRET_KEY=${API_SECRET_KEY}  
    ports:
      - "5000:5000"
    depends_on:
      mssql:
        condition: service_healthy
      mongo:
        condition: service_healthy
      neo4jdb:
        condition: service_healthy
    volumes:
      - ./backend-disc:/src
      - /src/backend-disc/bin
      - /src/backend-disc/obj
      - /src/class-library-disc/bin
      - /src/class-library-disc/obj
    user: root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend-disc:
    container_name: frontend-disc
    build:
      context: ./frontend-disc
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:5000/api
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-disc:/app
      - /app/node_modules
    depends_on:
      - backend-disc
  seeder:
    container_name: disc-seeder
    build:
      context: .
      dockerfile: /backend-disc/seeder/Dockerfile
    depends_on:
      mssql:
        condition: service_healthy
    env_file:
      - .env
    command: sh -c "/app/entrypoint.sh"
    deploy:
      replicas: 1    # 0 prevents seeder from starting automatically
# to run with seeder: docker compose up -d --scale seeder=1

volumes:
#   mssql-data:
  mongo_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:

