version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: disc-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -Q 'SELECT 1' -C -b"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend-disc:
    container_name: backend-disc
    build:
      context: .               
      dockerfile: backend-disc/backend-disc/Dockerfile
    env_file:
      - .env  # ðŸ‘ˆ loads environment variables from .env file
    ports:
      - "5000:5000"
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./backend-disc:/src/backend-disc
      - ./class-library-disc:/src/class-library-disc 

  frontend-disc:
    container_name: frontend-disc
    build:
      context: ./frontend-disc
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:5000/api
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-disc:/app
      - /app/node_modules
    depends_on:
      - backend-disc

volumes:
  mssql-data:

